### ISSUE TITLE
Pip check fails due to missing requirement

### ISSUE THREAD

**Issue by Zeitsperre** [conda-forge/pymbolic-feedstock#19]
When running tests for a dependency that uses `pymbolic`, my `pip check` step is failing due to a missing dependency:
```
pymbolic 2024.2 requires useful-types, which is not installed.
```
I can see that this has been disabled in the conda recipe, but would it be possible to mark this as a development-only dependency in the pip package and tag a new version?

Thanks!

**Comment by inducer** [comment]
https://pypi.org/project/pymbolic/2024.2.1/
